### ISSUE TITLE
handle_message does not log the appropiate queue

### ISSUE THREAD

**Issue by zoraida** [javierarilos/bashtasks#2]
Always assumes that the queue will be TASK_REQUESTS_POOL
    def handle_message(ch, method, properties, body):
        msg = json.loads(body.decode('utf-8'))
        logger.debug(">>>> msg received: %s from queue %s : correlation_id %d command: %s",
                     curr_th_name, TASK_REQUESTS_POOL, msg['correlation_id'], msg['command'][:50])

**Comment by javierarilos** [comment]
well spotted. 
you are right, pls send a PR. 
thanks.

**Comment by javierarilos** [comment]
closed by PR related to:
https://github.com/javierarilos/bashtasks/issues/3
